database:
  host: localhost
  port: 3306
  username: root
  password:
  database: cutepet
  charset: utf8

app:
  port: 8080
  debug: true
  log_level: debug
  secret_key: testsecret
  env: local

api_keys:
  google: test-google-api-key
  facebook: test-facebook-api-key